language: cpp
compiler: g++
dist: trusty
env:
    matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release
script: mkdir build && pushd build && cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
