version: 2
jobs:
    build:
        docker:
            - image: gcc:6
        steps:
            - checkout
            - run:
                name: "Pull Submodules"
                command: |
                    git submodule init
                    git submodule update --remote
            - run:
                name: Installing SUDO
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Install CMAKE
                command: 'apt-get update && sudo apt-get install -y cmake'
            - run:
                name: Install Dependencies
                command: 'sudo apt-get install -y python-dev'
            - run:
                name: CMake configure
                command: 'cmake -H. -Bbuild'
            - run:
                name: Make
                command: 'cmake --build build'
