version: 2
jobs:
    build:
        docker:
            - image: gcc:6
        steps:
            - checkout
            - run:
                name: Installing SUDO
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Install CMAKE
                command: 'apt-get update && sudo apt-get install -y cmake'
            - run:
                name: CMake configure
                command: 'mkdir -p build && cd build'
            - run:
                name: Make
                command: 'cmake .. && make'
